### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mmirman** [anarchy-ai/LLM-VM#1]
We need documentation for the entire project, and each sub-folder, and part.  And documentation for each function in the code itself, and a standard/programatic way to display documentation

**Comment by mmirman** [comment]
Will take suggestions about which docs viewer to use!

**Comment by mmirman** [comment]
Tasks:

- [ ] Add "example usages" to main README 
- [ ] Add "what is this project" section to main README
- [ ] Add "Why use this project" section  to main README
- [ ] Add "How does this project compare with others" to main README
- [ ] Add "How to contribute" to main README
- [ ] Add "How to get in touch" to main README
- [ ] Add "Acknowledgements" to main README
- [ ] Add a logo to main README
- [ ] Add a issue-tracker/stats/star graph to main README
- [ ] Add full and proper README to REBEL (https://github.com/extensional/REBEL) here, and make it proper with an experiments/results section and reproducability like seen here: https://github.com/eth-sri/eran 
- [ ] Add a issue-tracker/stats to main README

**Comment by cartazio** [comment]
@abhigya-sodani  whats left on this ticket?

**Comment by abhigya-sodani** [comment]
I don't think we have an issue tracker or a stars tracker yet.

**Comment by ajn2004** [comment]
I'm working on that right now

**Comment by abhigya-sodani** [comment]
@ajn2004 can I close this ticket now?

**Comment by ajn2004** [comment]
Sure
