### ISSUE TITLE
generalized constrained token inference interface

### ISSUE THREAD

**Issue by cartazio** [anarchy-ai/LLM-VM#106]
@itsmeashutosh43 and @VictorOdede I would love your feedback and Ideas on this

prompted by thinking about what we want out of regex/grammar constrained LLM inference, we've realized that we should just embrace having a more generic interface which those would be examples of.

I'm very much not familiar with python best practice, but heres my attempt at specifying it from a Types and stuff perspective thats slightly simplified. 

```python
"this is crudely our current api"
Class LLM(ABC):
   model : AbstractHF_Model
   tokenizer : Abstract_HF_Tokenizer
   genToken : List[Token] -> Map( Token_ID ,Log_Probability )

   generate_simple : ... bunch of stuff we pass to hf generate -> Async( String) 
"""generate_simple is our current generate """

   generate_with_Constraints : TokenConstraint -> ... same as above -> Async( String )

""" So lets talk about TokenConstraint!
"""
class TokenConstraint(ABC):

     constraint_type : type // the type of constraints we wanna have
     state_type : type //  this should be frozen/immutable, but i'll describe stuff in a way that maybe kinda works either way
     copy_state : 
     def is_valid (constraint : constraint_type ,  prefix : List of Tokens) ->  Bool : 

     def allowed_transitions(constraint: constraint_type, prefix : List of Token_id, tk : Tokenizer) -> Set(Token_id) : 

     def construct_state(constraint: constraint_type, prefix : List of Token_id, tk : Tokenizer) -> Union[None, state_type]
     // returns a state that *may* allow faster enumeration/checking of what tokens are allowed transitions next

     construct_crude_filter_set (constraint: constraint_type,tk : tokenizer,)-> Set [TokenID]
    // in eg a regex, this might be something like 
    // "the set of tokens that include only the character classes reference in the regexp"
   // it might be 

   // if we have anything complicated in constructing the current state, this should be *much* 
   // faster for filtering tokens 
   allowed_transitions_from_state (constraint : constraint_type, tk : tokenizer, st : state_type ) -> Set[token id]

    def copy_state(state : state_type)-> state_type 
   // if the state is immutable/frozen this should be the identity function 


```

something like this could maybe be the generic interface for constrained inference perhaps? i'm glossing over a lot of details like we're actually gonna be zeroing out the set of token indices that aren't in these sets in the log probability vectors, and all the mapping to and from tokenid <-> strings, and also the fact that we can do token constraint computation in paralell with running the gen_next_token_inference step

also in principle, things should  be such that we can have instances of this interface that correspond with 
logically `And` or `Or` or `Xor` or `Nand`together any two constraint languages I think?

**Comment by cartazio** [comment]
derp, posted before done editing

**Comment by cartazio** [comment]
anyways, this is just my fuzzy thoughts, @itsmeashutosh43 and @VictorOdede , honestly you guys can drive the figuring this out design wise

**Comment by VictorOdede** [comment]
I think it would be more intuitive to implement 2 separate classes for `generate_simple` and `generate_with_constraints` where they both inherit from the same parent class. Also would this mean a rewrite of the current `onsite_llm` implementation?

**Comment by VictorOdede** [comment]
For the `TokenConstraint` class, what other types of constraints are we looking to add apart from regex?

**Comment by VictorOdede** [comment]
Everything else is kinda straight forward since it can all be done in parallel with next token generation using a logit processor. I just need some clarification on what you mean by `state_type` and `copy_state`?

**Comment by mmirman** [comment]
> generic interface which those would be examples of.

I'd like to point out that "those being examples" of a generic interface does by no means imply this is trivial.  Compiling regex to DFAs is a pain.    These languages are important.

**Comment by VictorOdede** [comment]
> 

After doing a bit more research I now understand that compiling regex to DFAs is not as straight-forward as I thought. However, I've read through the [lmql paper](https://arxiv.org/abs/2212.06094) and they expound on the idea of partial evaluation and final semantics to evaluate the state of a generated sequence with regard to a given constraint expression. Using this concept we can eagerly prune a subset of valid tokens in the `crude_filter_set` that guaranteed to violate the expression. Will try to implement these ideas for generating the final mask for `allowed_transitions_from_state`. Feel free to correct me if there's something I'm missing

**Comment by VictorOdede** [comment]
I currently have a partial solution for this issue but I need some clarification on implementing the language constraints. Is the process to parse cfg to regex then compile regex to dfa then use the dfa to filter accepted tokens?

**Comment by VictorOdede** [comment]
Hey @cartazio, I found a way to implement cfg constraints without needing to scan the entire vocabulary for each generation. Since the outlines lib doesn't support this yet, can I add it to Abhighya's guided generation implementation?

**Comment by mmirman** [comment]
@VictorOdede  Is this done?

**Comment by VictorOdede** [comment]
Yes. This was addressed in https://github.com/anarchy-ai/LLM-VM/pull/154
