### ISSUE TITLE
issues finding settings.toml on a fresh install

### ISSUE THREAD

**Issue by abhigya-sodani** [anarchy-ai/LLM-VM#107]
```
 File "quickstart_finetune.py", line 5, in <module>
    from llm_vm.config import settings
  File "C:\Users\Abhigya Sodani\Anaconda3\lib\site-packages\llm_vm\config.py", line 55, in <module>
    if settings.big_model not in MODELS_AVAILABLE:
  File "C:\Users\Abhigya Sodani\Anaconda3\lib\site-packages\dynaconf\base.py", line 144, in __getattr__
    value = getattr(self._wrapped, name)
  File "C:\Users\Abhigya Sodani\Anaconda3\lib\site-packages\dynaconf\base.py", line 309, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'Settings' object has no attribute 'BIG_MODEL'
```

We need to replicate and fix these issues with dynaconf. I have this issue when I clone the repo and run pip run . .

**Comment by yujong-lee** [comment]
It happens to me in my M1 Mac too.

**Comment by yujong-lee** [comment]
I am able to reproduce this and fix it.

In my case, I newly install python using `pyenv install`. After using it as `pyenv global` and run `quickstart`, I got:
<img width="1295" alt="Screenshot 2023-08-06 at 10 49 23 PM" src="https://github.com/anarchy-ai/LLM-VM/assets/61503739/30cb39f8-22b7-49dc-8221-129c8b20c479">

We can see that in the console, `Source Directory` and `Project Root` is wrong. So we can not find `settings.default.toml`

At this state, this is my `os.sys.path`.
<img width="1649" alt="Screenshot 2023-08-06 at 10 54 01 PM" src="https://github.com/anarchy-ai/LLM-VM/assets/61503739/a6c75957-3582-45d9-a324-3b9d08b584d6">


After appending correct path to `os.sys.path`, (or run `pip3 install --editable .`), it works.
![Screenshot 2023-08-06 at 11 08 26 PM](https://github.com/anarchy-ai/LLM-VM/assets/61503739/85edc8d9-64e7-4786-9b22-fe0ab0c8e259)

**Comment by dorkitude** [comment]
@yujong-lee Thank you for reproducing.  I'll follow your steps to repro, and take a look at the config setup now (unless you'd like to fix it directly)


Indeed, many of us run `pip install --editable .` as a matter of course (working on things that touch the webserver while running the service itself), but this is not a good developer experience for people who just want to _use_ it instead of working on it.

**Comment by abhigya-sodani** [comment]
@cartazio should we close this?

**Comment by cartazio** [comment]
it should be resolved now yeah,
