### ISSUE TITLE
Data_synthesis fix

### ISSUE THREAD

**Issue by abhigya-sodani** [anarchy-ai/LLM-VM#108]
Currently data_synthesis.py asks GPT to generate all the datapoints in one call. This leads to many issues with many many incorrect datapoints being made and not enough datapoints being made. I fixed this in the experimentation_finetuning branch, and that approach of data synthesis needs to be brought to main and made robust (my current implementation is for research not deployment). 

One thing that needs to be done is semantic similarity checking the way that the current data_synthesis.py does. Also my implementation in experimentation_finetuning also does not support lists as inputs, and this needs to be added as well.

**Comment by bilal-aamer** [comment]
@abhigya-sodani could you assign me this issue.

**Comment by abhigya-sodani** [comment]
https://github.com/anarchy-ai/LLM-VM/issues/11
