### ISSUE TITLE
Add "model" as an optional parameter to generate/finetune function in onsite_llm.py

### ISSUE THREAD

**Issue by abhigya-sodani** [anarchy-ai/LLM-VM#109]
Right now in optimizer.py on line 238 
```
completion = self.call_small(prompt = dynamic_prompt.strip(), model=model, **kwargs)

```

we call the small model (accessing the generate function) with the model parameter. Right now this does not do anything, we need to be able to provide a .pt file to that parameter and then call load_model (also defined in onsite_llm.py) in order to load that .pt file as the model to use. This needs to be done in the finetune function as well.

**Comment by ajay-vishnu** [comment]
Hey, I wanna work on this issue. Can you assign me the task?
