### ISSUE TITLE
Get HuggingFace Kwargs working on the optimizer.complete endpoint

### ISSUE THREAD

**Issue by abhigya-sodani** [anarchy-ai/LLM-VM#113]
All HuggingFace arguments need to work on the optimizer.complete endpoint as well. For the complete endpoint this means the all arguments for the Huggingface .generate function must be able to be added to the optimize.complete function as well. Currently, this not something I was able to do with the ``` max_new_tokens ``` parameter, for example.

**Comment by Cosmogyrall** [comment]
Can anyone please describe this issue in more detail?

**Comment by VictorOdede** [comment]
Closed by #366
