### ISSUE TITLE
Connect to vector databases to supplement model memory/dynamically generate prompts

### ISSUE THREAD

**Issue by grepfruit19** [anarchy-ai/LLM-VM#131]
This was something I've looked into at a previous project I was working on, but in that project we struggled a lot with context length, as many of our inferences had a lot of irrelevant context for any given prompt, but we still needed that context for when it was relevant. Connecting to vector databases in order to keep contexts short while still providing relevant information.

**Comment by mmirman** [comment]
@cartazio @abhigya-sodani This is something else thats done at chat.dev that we need to pull into this project!
