### ISSUE TITLE
Move files from main directory 

### ISSUE THREAD

**Issue by INF800** [anarchy-ai/LLM-VM#142]
Files like 

* [quickstart.py](https://github.com/anarchy-ai/LLM-VM/blob/main/quickstart.py)
* [quickstart_REBEL.py](https://github.com/anarchy-ai/LLM-VM/blob/main/quickstart_REBEL.py)
* [quickstart_finetune.py](https://github.com/anarchy-ai/LLM-VM/blob/main/quickstart_finetune.py)
* [quickstart_finetune_load.py](https://github.com/anarchy-ai/LLM-VM/blob/main/quickstart_finetune_load.py)
* [quickstart_guided.py](https://github.com/anarchy-ai/LLM-VM/blob/main/quickstart_guided.py)

can be moved to `/examples` directory.

**Comment by cartazio** [comment]
good idea
