### ISSUE TITLE
Replace endpoint in docs

### ISSUE THREAD

**Issue by INF800** [anarchy-ai/LLM-VM#146]
Replace `https://localhost:3002/` with `http://localhost:3002/v1/complete` in SERVER_API.md

> #### Submitting a Request to the LLM
> 
> Post requests can be sent to this endpoint `https://localhost:3002/` in the following format:

**Comment by jankrom** [comment]
I am interested on working on this issue!

**Comment by VictorOdede** [comment]
Fixed by #175
