### ISSUE TITLE
Softcode number of examples and variance for data synthesis

### ISSUE THREAD

**Issue by INF800** [anarchy-ai/LLM-VM#148]
Pass `0.87` (variance) and `50` (number of examples) in `data_synthesis.DataSynthesis(0.87, 50)` through constructor `__init__` instead of hardcoding as in: 

https://github.com/anarchy-ai/LLM-VM/blob/7a5877b6adb2a71892203a71ac2095a01357bb1b/src/llm_vm/completion/optimize.py#L183

**Comment by daspartho** [comment]
opened #246
