### ISSUE TITLE
ERROR: Package 'llm-vm' requires a different Python: 3.9.6 not in '>=3.10'

### ISSUE THREAD

**Issue by saragracelien** [anarchy-ai/LLM-VM#164]
I was trying to install Anarchy but faced some issues with the Python version. 

I tried `conda create -n myenv python=3.9.6` but it did not work.

**Comment by mmirman** [comment]
1. Make project requirements clearer
2. Add an install script.

**Comment by saragracelien** [comment]
So I did `conda create -n myenv python=3.10` but it did not work. Everytime I checked the version using `python3 --version` it kept showing `Python 3.9.6` 

since I was using VS code, I found that if I changed the interpreter path and restarted VS code it finally worked. 

<img width="536" alt="Screenshot 2023-08-29 at 9 35 58 AM" src="https://github.com/anarchy-ai/LLM-VM/assets/56749249/d2d5fa5e-5990-4ac3-bdde-f60f263ead71">

**Comment by INF800** [comment]
Are these the same steps you followed?

```shell
(base ) $ conda create -n myenv python=3.10
(base) $ conda activate myenv
(myenv) $ python --version
```

Note how `base` turns into `myenv` upon activating the environment

`

**Comment by Lioncat2002** [comment]
Hello!
I would like to work on this

**Comment by mmirman** [comment]
You are free to work on it @Lioncat2002, but we can't assign it to you until you are a full contributor as per #contributing-guide in discord.

**Comment by Lioncat2002** [comment]
Ahh cool @mmirman 
So I was thinking of possible solution for this, and a simple one would be to make a bash script ig?
The users can directly run the script to get the repository work.

**Comment by vivasvan1** [comment]
What's the goal of this issue?

**Comment by bilal-aamer** [comment]
@VictorOdede Is this issue solved?

**Comment by bjornaer** [comment]
max.schulkin@gmail.com
