### ISSUE TITLE
TypeError: `Chat_GPT.finetune()` and `GPT3.finetune()` takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by rozeappletree** [anarchy-ai/LLM-VM#165]
When trying to fine-tune `small_model='gpt'` , error is thrown 

```
TypeError: GPT3.finetune() takes 4 positional arguments but 5 were given
```

Also, while trying to fine-tune `small_model='chat_gpt'`, similar error is thrown
```
TypeError: Chat_GPT.finetune() takes 4 positional arguments but 5 were given
```
Instead of 
```
fine-tuning isn't supported by OpenAI on this model
```
As in: 

https://github.com/anarchy-ai/LLM-VM/blob/b2e0cdad6a3d01c8812d31266bb84c9111fb1784/src/llm_vm/onsite_llm.py#L443-L445

<BR><BR>

This happens because in the below line, `small_model_filename` is passed

https://github.com/anarchy-ai/LLM-VM/blob/b2e0cdad6a3d01c8812d31266bb84c9111fb1784/src/llm_vm/completion/optimize.py#L276

But both `.finetune()` methods for `chat_gpt` and `gpt` do not take `small_model_filename` as one of the parameters:

https://github.com/anarchy-ai/LLM-VM/blob/b2e0cdad6a3d01c8812d31266bb84c9111fb1784/src/llm_vm/onsite_llm.py#L384

https://github.com/anarchy-ai/LLM-VM/blob/b2e0cdad6a3d01c8812d31266bb84c9111fb1784/src/llm_vm/onsite_llm.py#L443

They must be `finetune(self, dataset, optimizer, c_id, small_model_filename=None): ...`. This can be a temporary fix but will need an ABC so that this does not happen again in the future.

**Comment by VictorOdede** [comment]
Fixed by #262
