### ISSUE TITLE
Create docker image and post in dockerhub

### ISSUE THREAD

**Issue by TheRealVish** [anarchy-ai/LLM-VM#169]

**Comment by SainiAditya1** [comment]
@mmirman Please Assign me this , I would love to do this.

**Comment by SainiAditya1** [comment]
Please give more explanation if possible about this.

**Comment by mmirman** [comment]
@SainiAditya1 It looks like @TheRealVish is working on this, and check out the new guidelines around assignment: https://anarchy.ai/contributing/community_development#becoming-an-official-contributor
