### ISSUE TITLE
"LlamaForCausalLM" is not defined

### ISSUE THREAD

**Issue by TheRealVish** [anarchy-ai/LLM-VM#183]
https://github.com/anarchy-ai/LLM-VM/blob/84d14fad9e74829da1ff710b3cc1f08711ddddec/src/llm_vm/onsite_llm.py#L301C16-L301C16

**Comment by INF800** [comment]
@TheRealVish I think it is not complete yet. You may need to reopen it? I don't see the required import statement

**Comment by ChinmayK0607** [comment]
Hey @TheRealVish , I think there is a problem with the imports, as it has not been imported and thus not defined

**Comment by us** [comment]
duplicated #158

**Comment by us** [comment]
@TheRealVish I noticed the issue you raised, and I'd love to help you out, but I need a bit more info to understand what's going on. Could you please share some extra details with us? It'll make solving this problem a breeze!

1. **How did you come across this issue?**
   It'd be great to know what you were up to when you ran into this problem. Did it happen during a specific task, script, or under certain conditions?

2. **Steps to Reproduce:**
   We'd really appreciate it if you could walk us through the steps to recreate the error. That way, we can give it a whirl on our end and figure out what's going wrong.

3. **Full Error Message:**
   The full error message is like a clue in solving a mystery. Could you share it exactly as it popped up on your screen?

4. **Tell us about your setup:**
   - **Python Version:** What version of Python are you using?
   - **Virtual Environment:** Are you working in a virtual environment? Let us know!
   - **Package Versions:** You can check which Python packages are installed and their versions by running `pip list`.

We're here to make your experience smoother, so your insights are super helpful. Providing these details will help us get to the bottom of things faster.

**Comment by fedegr** [comment]
I think this is solved on [PR#162](https://github.com/anarchy-ai/LLM-VM/pull/162/files)
