### ISSUE TITLE
Add more tooling for Rebel agent

### ISSUE THREAD

**Issue by VictorOdede** [anarchy-ai/LLM-VM#189]
Current agents only support a handful of tools, add implementations for a few more tools

**Comment by abhigya-sodani** [comment]
You can add any arbitrary tool (and GET/POST request) to the REBEL agent, the tools that are there are example tools for k-shot prompting

**Comment by VictorOdede** [comment]
> You can add any arbitrary tool (and GET/POST request) to the REBEL agent, the tools that are there are example tools for k-shot prompting

Ow, okay. I get it now. Will just go ahead and close this issue.

**Comment by VictorOdede** [comment]
Non-issue
