### ISSUE TITLE
Update agents to use optimizing completion API.

### ISSUE THREAD

**Issue by mmirman** [anarchy-ai/LLM-VM#19]
This will require re-running of tests.  It should be possible to turn off this behavior at a high level.  Blocked by both #2  and #18

**Comment by cartazio** [comment]
Is this task done ?

**Comment by abhigya-sodani** [comment]
Not yet

**Comment by mmirman** [comment]
@abhigya-sodani I will note this isn't exactly straightforward as a lot of the agent calls use highly-varying prompts and the optimizing endpoints are meant to improve cases where the prompts don't vary between calls

**Comment by cartazio** [comment]
@abhigya-sodani  is this done?

**Comment by abhigya-sodani** [comment]
I don't think we should do this. REBEL will not work with anything except GPT/Chat_GPT. Our completion API can be configured to be any LLM, and will cause REBEL to fail.

**Comment by cartazio** [comment]
so we should close this ticket?
