### ISSUE TITLE
Implement Code Llama in LLMVM

### ISSUE THREAD

**Issue by VictorOdede** [anarchy-ai/LLM-VM#190]
Add implementation for code-llama 7B/13B/34B

**Comment by VictorOdede** [comment]
Add implementation for code-llama 7B/13B/34B

**Comment by fedegr** [comment]
CodeLLama hasn't been released yet on HuggingFace transformers. [It is expected to be released on v4.33](https://huggingface.co/blog/codellama#how-to-use-code-llama)

**Comment by VictorOdede** [comment]
> CodeLLama hasn't been released yet on HuggingFace transformers. [It is expected to be released on v4.33](https://huggingface.co/blog/codellama#how-to-use-code-llama)

This isn't necessarily huggingface dependent since the model is publicly available
