### ISSUE TITLE
ChatGPT fine tune should not exit the program

### ISSUE THREAD

**Issue by fedegr** [anarchy-ai/LLM-VM#196]
Chat_GPT.finetune should raise an exception instead of exiting the program, so LLM-VM can be used as an external library.

> [Chat_GPT.finetune](https://github.com/anarchy-ai/LLM-VM/blob/dc02e9b712431314d21afb01bd1566642962a3ec/src/llm_vm/onsite_llm.py#L470):
>  ```python
>    def finetune(self, dataset, optimizer, c_id):
>         print("fine tuning isn't supported by OpenAI on this model", file=sys.stderr)
>         exit()
> ```

**Comment by fatma-hmz** [comment]
Hi there ! I'm really excited to contribute to this project! I've come across Issue #196 labeled as "good for beginners," and it seems like a great opportunity for me to get involved and learn more about the project. I'd like to express my interest in working on this issue.
 I'll make sure to follow the project's guidelines and any specific instructions provided. Looking forward to becoming a full contributor and contributing to the project's succes

**Comment by mmirman** [comment]
I'm going to accept #263 over #242 as its simpler and this is a simple bug!
