### ISSUE TITLE
Import errors in test_data_synthesis 

### ISSUE THREAD

**Issue by johntharian** [anarchy-ai/LLM-VM#197]
Getting the following error when running pytest

`ImportError while importing test module 'E:\anarchy\LLM-VM\tests\test_data_synthesis.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\ASUS\anaconda3\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_data_synthesis.py:2: in <module>
    from dotenv import load_dotenv
E   ModuleNotFoundError: No module named 'dotenv'`

**Comment by pratik-joshi02** [comment]
@mmirman both test_data_synthesis.py and test_optimize.py cannot run because we are not installing dotenv. 
@johntharian Just run pip3 install python-dotenv. pip3 install dotenv wont work.

**Comment by johntharian** [comment]
![image](https://github.com/anarchy-ai/LLM-VM/assets/55285376/7aaf4fb9-0272-4b19-a553-234b97ae02e0)

@pratik-joshi02  This is what I get when I run pytest after pip3 install python-dotenv

**Comment by pratik-joshi02** [comment]
Can i see the pip list
Also your python version is 2.10 right. 
You also need to change these lines in test_data_synthesis.py
from llm_vm.completion import data_synthesis
instead of  import data_synthesis
and
from llm_vm.completion.optimize import *
instead of from optimize import *

**Comment by johntharian** [comment]
The python version is 3.11.4

(anarchy) E:\anarchy\LLM-VM>python --version
Python 3.11.4

(anarchy) E:\anarchy\LLM-VM>pip list
Package               Version
--------------------- -----------
accelerate            0.22.0
aiohttp               3.8.5
aiosignal             1.3.1
annotated-types       0.5.0
asttokens             2.2.1
async-timeout         4.0.3
attrs                 23.1.0
beartype              0.15.0
beautifulsoup4        4.12.2
blinker               1.6.2
blis                  0.7.10
bs4                   0.0.1
catalogue             2.0.9
certifi               2023.7.22
charset-normalizer    3.2.0
click                 8.1.7
cloudpickle           2.2.1
colorama              0.4.6
comm                  0.1.4
confection            0.1.1
cymem                 2.0.7
dataclasses-json      0.5.14
debugpy               1.6.7.post1
decorator             5.1.1
dynaconf              3.2.2
en-core-web-md        3.6.0
filelock              3.12.3
Flask                 2.3.3
Flask-Cors            4.0.0
frozenlist            1.4.0
fsspec                2023.6.0
greenlet              2.0.2
huggingface-hub       0.16.4
icontract             2.6.2
idna                  3.4
interegular           0.3.2
ipykernel             6.25.1
ipython               8.14.0
itsdangerous          2.1.2
jedi                  0.19.0
Jinja2                3.1.2
joblib                1.3.2
jupyter_client        8.3.0
jupyter_core          5.3.1
langchain             0.0.279
langcodes             3.3.0
langsmith             0.0.32
lark                  1.1.7
Levenshtein           0.21.1
llama-index           0.8.16
llm-vm                0.1.0
MarkupSafe            2.1.3
marshmallow           3.20.1
matplotlib-inline     0.1.6
mpmath                1.3.0
multidict             6.0.4
murmurhash            1.0.9
mypy-extensions       1.0.0
nest-asyncio          1.5.7
networkx              3.1
nltk                  3.8.1
numexpr               2.8.5
numpy                 1.25.2
openai                0.28.0
outlines              0.0.8
packaging             23.1
pandas                2.1.0
parso                 0.8.3
pathy                 0.10.2
perscache             0.6.1
Pillow                10.0.0
pip                   23.2.1
platformdirs          3.10.0
preshed               3.0.8
prompt-toolkit        3.0.39
psutil                5.9.5
pydantic              2.3.0
pydantic_core         2.6.3
python-dateutil       2.8.2
python-dotenv         1.0.0
python-Levenshtein    0.21.1
pytz                  2023.3
PyYAML                6.0.1
pyzmq                 25.1.1
rapidfuzz             3.2.0
regex                 2023.8.8
requests              2.31.0
safetensors           0.3.3
scikit-learn          1.3.0
scipy                 1.11.2
sentence-transformers 2.2.2
sentencepiece         0.1.99
setuptools            68.0.0
six                   1.16.0
smart-open            6.3.0
soupsieve             2.4.1
spacy                 3.6.1
spacy-legacy          3.0.12
spacy-loggers         1.0.4
SQLAlchemy            2.0.20
srsly                 2.4.7
stack-data            0.6.2
sympy                 1.12
tenacity              8.2.3
thinc                 8.1.12
threadpoolctl         3.2.0
tiktoken              0.4.0
tokenizers            0.13.3
torch                 2.0.1
torchvision           0.15.2
tornado               6.3.3
tqdm                  4.66.1
traitlets             5.9.0
transformers          4.32.1
typer                 0.9.0
typing_extensions     4.7.1
typing-inspect        0.9.0
tzdata                2023.3
urllib3               1.26.16
wasabi                1.1.2
watchdog              3.0.0
Werkzeug              2.3.7
wheel                 0.38.4
xdg                   6.0.0
yarl                  1.9.2

**Comment by pratik-joshi02** [comment]
Well try restarting the terminal. The problem with the test scripts are that they have not been updated. The open API key is not passed and there are a lot of small bugs. I will try solving this and adding a pull request.

**Comment by johntharian** [comment]
Hey @pratik-joshi02  is it working for you after installing python-dotenv?
I tried adding it to pyproject.toml and made the changes to how we import data_synthesis and optimize and its still not working. Its giving the same error

**Comment by pratik-joshi02** [comment]
The test_data_synthesis is working but not the test_optimize.

**Comment by VictorOdede** [comment]
Fixed in #366
