### ISSUE TITLE
Pull in agents from LLM-VM-add-agents branch

### ISSUE THREAD

**Issue by mmirman** [anarchy-ai/LLM-VM#2]
- These need a standardized interface (so they take tool descriptions of the same format), 
- They should also be updated to use non-api tools (just closures).

**Comment by Nike682631** [comment]
Hi @mmirman ,
I'd like to work on this if you could guide me a bit on how I should proceed on this!

**Comment by mmirman** [comment]
@Nike682631 Yes! post about it in the discord/engineering channel and lets discuss there

**Comment by mmirman** [comment]
@AB3000 If you could briefly describe the state of that branch that would be super helpful!

**Comment by mmirman** [comment]
- [ ] These need a standardized interface (so they take tool descriptions of the same format), 
- [ ] standardized documentation, 
- [ ] to be updated to use the optimizing completion API, 
- [ ] and test suites that actually work. 
- [ ] They should also be updated to use non-api tools (just closures).

**Comment by cartazio** [comment]
This should be done right ?
