### ISSUE TITLE
Developer documentation builder

### ISSUE THREAD

**Issue by VictorOdede** [anarchy-ai/LLM-VM#241]
Can be done using `sphinx` - https://www.sphinx-doc.org/en/master/

**Comment by BlackReaper333** [comment]
So I found this tool, that automatically generates documentation including call stacks for the entire code, called doxygen (https://www.doxygen.nl/) . This tool has the same functionality of exporting the documentation to latex, html, and many other formats. I have attached the html output of this to #engineering discord channel. Would this work?
[html.zip](https://github.com/anarchy-ai/LLM-VM/files/12578670/html.zip)

**Comment by grgkaran03** [comment]
What exactly needs to be done here?

**Comment by guptaaryan16** [comment]
@mmirman I would like to take up the issue, first time contributor though

**Comment by daredevilteja** [comment]
I would like to work on this issue.

**Comment by VictorOdede** [comment]
We're currently using Mintlify for this so I'll just close this issue until we decide to implement another doc builder.
