### ISSUE TITLE
Create a Glossary

### ISSUE THREAD

**Issue by zhsueh** [anarchy-ai/LLM-VM#258]
Create a document to put LLM-VM terms in, some of the new words will confuse developers. 
Written in markdown

**Comment by mmirman** [comment]
I love it

**Comment by ArgyPorgy** [comment]
I would like to work on this issue @mmirman. Will the glossary contain the LLM VM terms specifically or the general ML terms as well?

**Comment by Phantom-Harsh** [comment]
@zhsueh  and @mmirman , I am interested in working on this project. It would be my inaugural contribution to the Anarchy Github repository.

**Comment by eliazonta** [comment]
I'm interested as well, is there some resources or some skeleton that I could use in order to create this glossary?
file structure? arrange data in tables? 
Or should I use my common sense and we'll figure it out during the way?

if at least could be possible to have some details on the terms that you would like to collect I would be interested in doing it :)

**Comment by jankrom** [comment]
Addressed in #313

**Comment by yuqianlucy** [comment]
Mr.@mmirman, I am also very interested in creating the glossary, what are some tools or package or codes that can help build a useful glossary? Thank you!

**Comment by Abdevna** [comment]
Hello @VictorOdede, I am also pretty interested in creating the glossary and also it would be my first ever contribution!
Thank you!

**Comment by yuqianlucy** [comment]
> Mr.@mmirman, I am also very interested in creating the glossary, what are some tools or package or codes that can help build a useful glossary? Maybe be we can also add an search bar to let the user to search the words they want to look for inside the dictionary.Thank you!

Add search bar for searching vocabulary.

**Comment by mmirman** [comment]
Looking at this, dunno how this got dumped into a code repo.  This is inappropriate there where we're trying to keep things minimal.  This should be in anarchy.ai.   Also the point was to link terms to appropriate glossary definitions and come up with an automatic way of doing this.

**Comment by VictorOdede** [comment]
Closed by #313
