### ISSUE TITLE
Fine-tuning Support for OpenAI Model

### ISSUE THREAD

**Issue by sushmanthreddy** [anarchy-ai/LLM-VM#269]
In the `finetune` method of the code, it appears that fine-tuning is not currently supported for the OpenAI model. The method raises an exception indicating this limitation. However, there's commented-out code that suggests there might have been an attempt or a plan to support fine-tuning in the future.

```python
def finetune(self, dataset, optimizer, c_id):
    print("fine tuning isn't supported by OpenAI on this model", file=sys.stderr)
    raise Exception("fine tuning isn't supported by OpenAI on this model")
    # ... (rest of the method)

**Comment by sushmanthreddy** [comment]
@meganmerz I would like to work on this issue..

**Comment by mmirman** [comment]
@VictorOdede @abhigya-sodani Why isn't there finetuning support for OAI here?  I recall when I first made the optimizer endpoint there was finetuning for OAI

**Comment by abhigya-sodani** [comment]
Last I remember, there was finetuning for OpenAI too.

**Comment by sushmanthreddy** [comment]
@mmirman @abhigya-sodani it has been commented out as per the present version anarchy the code has been commented out and exception has been raised over there.
No fine tuning support for it

**Comment by mmirman** [comment]
@sushmanthreddy https://github.com/anarchy-ai/LLM-VM/blob/main/src/llm_vm/completion/optimize.py#L27 There is finetuning support for OAI just not in this file.  I'm asking @VictorOdede and @cartazio why not in this file

**Comment by VictorOdede** [comment]
> @sushmanthreddy https://github.com/anarchy-ai/LLM-VM/blob/main/src/llm_vm/completion/optimize.py#L27 There is finetuning support for OAI just not in this file. I'm asking @VictorOdede and @cartazio why not in this file

Not sure why it's not in this file but will look into it asap

**Comment by sushmanthreddy** [comment]
@VictorOdede have u got any update on this??
if any changes are needed pls let me knew

**Comment by VictorOdede** [comment]
@mmirman according to my understanding, finetuning for gpt 3.5 wasn't available at the time of writing this file. OpenAI just added support for this a few weeks ago

**Comment by VictorOdede** [comment]
Will have a look at the PR soon @sushmanthreddy

**Comment by VictorOdede** [comment]
Duplicate issue
