### ISSUE TITLE
What LLM flavors have explicit rng Seed being surfaces as optional input or something that can be part of the response metadata for reproducibility? ()

### ISSUE THREAD

**Issue by cartazio** [anarchy-ai/LLM-VM#27]

**Comment by cartazio** [comment]
this looks like hf-transformers has a nice story sometiems here

**Comment by mmirman** [comment]
@cartazio can you triage this?  I'm unsure if this is important rn

**Comment by cartazio** [comment]
we dont handle seeds in how we sample the tokens, but fine for now
