### ISSUE TITLE
fix ctransformers default arguments

### ISSUE THREAD

**Issue by cartazio** [anarchy-ai/LLM-VM#281]
currently 

https://github.com/anarchy-ai/LLM-VM/blob/main/src/llm_vm/onsite_llm.py#L305-L331

the model file and model uri should be keyword args for the init, and stuff like that needs cleanup

**Comment by bilal-aamer** [comment]
Hey @cartazio,

Is this something you mean?

```
def __init__(self, model_uri=None, model_file=None, tokenizer_kw_args={}, model_kw_args={}):
    if model_uri is not None:
        self.model_uri = model_uri
    if model_uri is None and self.model_uri is None:
        raise ValueError('A very specific bad thing happened.')

    self.model_file = model_file
.
.
.

```

**Comment by cartazio** [comment]
the keyword arguments should be set with a REPO and a filename by default,

like https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML and
llama-2-7b-chat.ggmlv3.q2_K.bin
<https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/blob/main/llama-2-7b-chat.ggmlv3.q2_K.bin>
 or something like that, i'm probably getting the uri slightly wrong :)

**Comment by cartazio** [comment]
looking at the example docs in pypi for ctransformers
```
from ctransformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("marella/gpt-2-ggml", hf=True)
tokenizer = AutoTokenizer.from_pretrained(model)
```
looks like we're not quite doing that ..

**Comment by bilal-aamer** [comment]
@cartazio Got a PR out on this

**Comment by cartazio** [comment]
Looking more closely I was just dumb, the code is correct
