### ISSUE TITLE
default small model assignment in `client.py`

### ISSUE THREAD

**Issue by daspartho** [anarchy-ai/LLM-VM#287]
https://github.com/anarchy-ai/LLM-VM/blob/058ee9d39d7b99e932f38f9a0e3aef0bd36484ff/src/llm_vm/client.py#L11-L19

In line 16 here, shouldn't the intended behavior be something like `if conf.settings.small_model is None: ` or am I missing something important here?

Gently pinging @cartazio after referring to git blame for the code!

**Comment by cartazio** [comment]
I think you’re correct! Good catch!!

**Comment by daspartho** [comment]
@cartazio should i make a quick pr to fix it?

**Comment by cartazio** [comment]
Totes.  Ping me and vik and it’ll be an easy merge.  Though test the change
locally first :)

**Comment by daspartho** [comment]
opened a PR #288
