### ISSUE TITLE
identify more robust output format for data synthesis

### ISSUE THREAD

**Issue by cartazio** [anarchy-ai/LLM-VM#29]
the first version uses JSON, which can often be malformed, and theres no good error recovery in that case, need to identify and switch to a more "error tolerant" self aligning format. (meaning we can skip a bad pair and recover useful outputs)

**Comment by cartazio** [comment]
i've a few ideas for this i'll try.

**Comment by mmirman** [comment]
XML is the key.  Its really the only key.  Foundation LLMs have a lot of XML in their outputs so are super-primed to output it.  Also you can scrub inputs by ensuring the tags are unlikely to be guessed.  

Also this is what LMQL is for!

**Comment by cartazio** [comment]
Good points. I’ll dig into this direction

**Comment by mmirman** [comment]
I do want to add regex and lmql to our platform btwBest,Matt==================Dr. Matthew Mirmanhttps://www.mirman.comOn 30 Jun 2023, at 7:15 PM, Carter Tazio Schonwald ***@***.***> wrote:﻿
Good points. I’ll dig into this direction

**Comment by cartazio** [comment]
should be a bit more robust, we can revisit this later
