### ISSUE TITLE
add formal-language (regex/grammars) querying to llm interaction

### ISSUE THREAD

**Issue by cartazio** [anarchy-ai/LLM-VM#30]
Example:
```
> r = complete(prompt="how many eyes do cats have, and how many eyes do spiders have?", output_filter_regex="\{ 'cats': [0-9]*, 'spiders': [0-9]* \}"
> print(r)
{ 'cats': 2, 'spiders': 8 }
```

Excuse my regex though, I'm a bit rusty. 

Like https://lmql.ai/ but with easier languages to use

**Comment by mmirman** [comment]
Note, this is blocked by running OSS LLMs with a Main.py #6

**Comment by abhigya-sodani** [comment]
> Note, this is blocked by running OSS LLMs with a Main.py #6

Should be unblocked now

**Comment by mmirman** [comment]
@abhigya-sodani Awesome!  This is honestly the coolest feature.

**Comment by ajitalapati** [comment]
Check this out: 

https://github.com/microsoft/guidance

**Comment by dorkitude** [comment]
Love this feature idea!

The example regex doesn't exactly work, though -- it seems more like a `re.findall` call matched with some form of templating?  But that might be over-fitting to the example

Can you give me 3-4 other examples of stuff we want this feature to support?

**Comment by mmirman** [comment]
prompt="speak in catinary (a cat/dog language I just made up:"

regex="((cat )|(dog ))*"

output:  cat cat cat dog cat dog dog dog

**Comment by itsmeashutosh43** [comment]
Do you want to parse the output or modify the likelihood of tokens appearing in the completion like in r[ellm](https://github.com/r2d4/rellm/tree/main)?

**Comment by cartazio** [comment]
latter, modify the probability vector over tokens to only allow ones that would be valid transitions of the grammar, zero out all the other tokens

**Comment by itsmeashutosh43** [comment]
I have opened a PR [here](https://github.com/anarchy-ai/LLM-VM/pull/100)

**Comment by bilal-aamer** [comment]
@mmirman, Is this issue resolved?

**Comment by mmirman** [comment]
@bilal-aamer see #106
