### ISSUE TITLE
move all the prints to using stderr by default?

### ISSUE THREAD

**Issue by cartazio** [anarchy-ai/LLM-VM#31]
its as simple as changing 
`print(s)` to `print(s,file=sys.stderr)`

at least,. i think that is a pretty reasonable change that is good engineering to do

**Comment by greydoubt** [comment]
import sys

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

# Now you can use eprint just like print, but it goes to stderr
eprint("An error has occurred")

**Comment by greydoubt** [comment]
### use this instead:
import sys

def stderr_decorator(func):
    def wrapper(*args, **kwargs):
        print(*args, file=sys.stderr, **kwargs)
    return wrapper

@stderr_decorator
def print_to_stderr(s):
    return s

print_to_stderr("An error has occurred")

**Comment by cartazio** [comment]
I’m totally a newb at modern python, what are the benefits of this approach? Also should the body function be func rather than print?

**Comment by cartazio** [comment]
I guess I mean I’d love to understand the reasoning for this style!

**Comment by mmirman** [comment]
I usually just use like mprint and then its less characters

**Comment by cartazio** [comment]
I’m failing to google mprint. What do you mean?

**Comment by mmirman** [comment]
I just mean name your helper print function which defaults to stderr mprint or smth

**Comment by cartazio** [comment]
Logging would be another good name.  Or at least eventually this will turn
into adhoc logging :)

**Comment by cartazio** [comment]
interesting idea! maybe after we have a solid configuration subsystem.
