### ISSUE TITLE
Error Running LLM - Symbol not found

### ISSUE THREAD

**Issue by AndrewGithinji** [anarchy-ai/LLM-VM#322]
The specific error is related to the sentencepiece library and a symbol not being found during the process of trying to run the LLM-VM.
I have already attempted a few troubleshooting steps such as updating the sentencepiece library, verifying Python compatibility, and ensuring library versions are compatible, but the issue still persists.
![Screen Shot 2023-10-10 at 11 29 22](https://github.com/anarchy-ai/LLM-VM/assets/107027477/7fb95067-a4ad-481b-bc1c-8da663349dd4)

**Comment by kshitiz305** [comment]
please share the full error

**Comment by AndrewGithinji** [comment]
Here's the full screenshot..
![Screen Shot 2023-10-18 at 17 34 01](https://github.com/anarchy-ai/LLM-VM/assets/107027477/23d590f8-3f23-4d47-bd07-d1c859678dfc)

**Comment by daredevilteja** [comment]
> Here's the full screenshot.. ![Screen Shot 2023-10-18 at 17 34 01](https://user-images.githubusercontent.com/107027477/276291523-23d590f8-3f23-4d47-bd07-d1c859678dfc.png)

Can you please give more detailed info like what you were trying to do when you encountered this error?

**Comment by VictorOdede** [comment]
Looked into your code and it seems that you're trying to use the chat_gpt model. For this to work you need to pass in your `openai_key` in the `big_model_config` attribute while initializing the client.

**Comment by AndrewGithinji** [comment]
Thanks @VictorOdede
