### ISSUE TITLE
Install script for Windows

### ISSUE THREAD

**Issue by VictorOdede** [anarchy-ai/LLM-VM#323]
We currently only have an install script for MacOS

**Comment by Avr-Arnold** [comment]
I run windows and can try and help if there are more specs here. Also, are all the python libraries windows compatible? I recently worked on some projects that were not and needed a VM/WSL. A good thing to clarify before going down a rabbit hole (like I did :) ).

**Comment by VictorOdede** [comment]
Hey @Avr-Arnold i think all the packages are compatible with Windows but if you find one that isn't feel free to raise an issue

**Comment by daredevilteja** [comment]
I want to take this up. There are 2 ways in which I'm thinking of addressing this issue:
1. We can use containerization software like docker to install the repo, we can fix the base image to linux. The advantage with this route is we need to maintain only one setup script and we don't need to maintain setup scripts for different oses.
2. There is a package manager for windows called winget, I try writing a powershell script such that required packages are installed from winget and the setup happens through powershell.

**Comment by daredevilteja** [comment]
I have added the installation instructions for Windows OS in the above mentioned PR

**Comment by daredevilteja** [comment]
Please check it @VictorOdede @abhigya-sodani
