### ISSUE TITLE
`peft` and `trl` not in dependencies

### ISSUE THREAD

**Issue by daspartho** [anarchy-ai/LLM-VM#326]
`peft` and `trl` not found when running the quickstart example.

<img width="830" alt="Screenshot 2023-10-13 at 7 50 02 PM" src="https://github.com/anarchy-ai/LLM-VM/assets/59410571/f14014bd-412b-4cd6-9fc0-f3df2f57b4d5">
<img width="817" alt="Screenshot 2023-10-13 at 7 50 19 PM" src="https://github.com/anarchy-ai/LLM-VM/assets/59410571/d69a18c6-a7f4-49e4-a7f4-19b988f6a7a2">

both `peft` and `trl` library not present in build dependencies while being used in the library.
https://github.com/anarchy-ai/LLM-VM/blob/7d2a52a63027bf32712409405a8df3697e5a9ec2/src/llm_vm/onsite_llm.py#L26-L27

**Comment by daspartho** [comment]
open PR to resolve #327

**Comment by bilal-aamer** [comment]
@daspartho Got the same issue a while back 👍🏼
