### ISSUE TITLE
Streamlit Fails - signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by MehmetMHY** [anarchy-ai/LLM-VM#340]
During the Anarchy hackathon, we planned on adding a frontend to our project using Streamlit. But we ran into this bug:

```
Project Root: /user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/llm_vm
2023-10-18 14:18:06.190 Uncaught app exception
Traceback (most recent call last):
  File "/user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/user/insightred/frontend.py", line 6, in <module>
    from main import update_data
  File "/user/insightred/main.py", line 7, in <module>
    import ai
  File "/user/insightred/ai.py", line 11, in <module>
    from llm_vm.client import client_build
  File "/user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/llm_vm/client.py", line 6, in <module>
    from llm_vm.completion.optimize import LocalOptimizer
  File "/user/.pyenv/versions/3.11.2/lib/python3.11/site-packages/llm_vm/completion/optimize.py", line 31, in <module>
    signal.signal(signal.SIGINT, exit_handler)
  File "/user/.pyenv/versions/3.11.2/lib/python3.11/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: signal only works in main thread of the main interpreter
^C  Stopping...
```

After some digging, the issue is occurring in `LLM-VM/src/llm_vm/completion/optimize.py`, specifically at line 31:
```
signal.signal(signal.SIGINT, exit_handler)
```

**Comment by MehmetMHY** [comment]
One work around I though about fixing this bug was by replacing this line:
```
signal.signal(signal.SIGINT, exit_handler)
```

With this instead:
```
if threading.current_thread() == threading.main_thread():        
    signal.signal(signal.SIGINT, exit_handler)
```

**Comment by MehmetMHY** [comment]
Here is the PR to fix this: https://github.com/anarchy-ai/LLM-VM/pull/341
☝️ Let me know what you all think

**Comment by galomari** [comment]
If for some reason you can’t avoid running the code in non-main thread you can conditionally set single handler only when in main thread: `import threading import signal. If threading.current_thread()==threading.main_thread():signal.signal(signal.SIGINT,exit_handler)`

**Comment by MehmetMHY** [comment]
> If for some reason you can’t avoid running the code in non-main thread you can conditionally set single handler only when in main thread: `import threading import signal. If threading.current_thread()==threading.main_thread():signal.signal(signal.SIGINT,exit_handler)`

Yup, that is what I added in my PR (https://github.com/anarchy-ai/LLM-VM/pull/341)
