### ISSUE TITLE
Create an Issue Template.

### ISSUE THREAD

**Issue by shubhusion** [anarchy-ai/LLM-VM#382]
### Description

This issue aims to establish a standardized issue template for this repository. Issue templates serve as essential guidelines for users and contributors when creating new issues, ensuring that relevant information is consistently provided. By implementing a well-defined template, we can streamline issue creation, enhance issue tracking, and improve communication within the repository. 

This issue will involve:

- Defining the template's structure
- Outlining the required content
- Establishing guidelines for use

We will also seek input and feedback from the community to ensure that the issue template aligns with our project's needs and goals.

### Goal

The goal of this issue is to create a structured and consistent issue template that benefits both the project maintainers and the community by improving issue reporting and tracking.

**Comment by VictorOdede** [comment]
We can do this later on because this will create a bottleneck for new contributors
