### ISSUE TITLE
Unable to pip install

### ISSUE THREAD

**Issue by suryachereddy** [anarchy-ai/LLM-VM#387]
When I `pip3 install --editable .`, I'm getting this following error:

`              ********************************************************************************
              Version '0.1.51 ' is not valid according to PEP 440.
      
              Please make sure to specify a valid version for your package.
              Also note that future releases of setuptools may halt the build process
              if an invalid version is given.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************`
              
This is likely due to a space at line 3 of pyproject.toml. The version must be `version = "0.1.51"` not `version = "0.1.51 "`. The package installs after this change.

**Comment by VictorOdede** [comment]
Hey @suryachereddy sorry about that. It's an issue with the whitespace after the version number. I've just pushed a fix for this so It should be working now.
