### ISSUE TITLE
working on Queuing_for_concurrent_requests_REST

### ISSUE THREAD

**Issue by lucylililiwang** [anarchy-ai/LLM-VM#391]

**Comment by VictorOdede** [comment]
Hey @lucylililiwang you need to open a PR linking to the issue by adding `Closes #issuenumber` in the description of your PR. Also, the Queuing issue has been labelled `someday` meaning it can't be fully implemented at the moment. We need to flesh out the REST api first. Kindly choose a more suitable issue to work on.
