### ISSUE TITLE
HuggingFace Token

### ISSUE THREAD

**Issue by AfamO** [anarchy-ai/LLM-VM#429]
**Describe the bug**
Hugging Face is asking for token to access and run Llam2 model

**To Reproduce**
1. Import Client from llm_vm 
2. Try performing completion request using llam2 as big_model.
4. Then run the python code . See the attached screen shot.
5. See error. See the attached screen shot

**Expected behavior**
Before invoking the model, Hugging Face expects a token having permission to the repo to be passed either via 
huggingface-cli login` or by passing `token=<your_token>`.

**Screenshots**
![llm_vm llama2 error](https://github.com/anarchy-ai/LLM-VM/assets/9824566/3ecb5f5b-d1b0-4607-8648-09e555903d7d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version The latest build. Just cloned from the main repo about 3 hours ago.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wansatya** [comment]
You can manage the HF login using `from huggingface_hub import login`

```
import sys
import os
# Import our client
from llm_vm.client import Client
# Import huggingface hub login
from huggingface_hub import login

# Login with HF API token
login(
    os.getenv("LLM_VM_HUGGINGFACEHUB_API_TOKEN")
)

# Instantiate the client specifying which LLM you want to use
client = Client(
    big_model='llama2'
)

# Put in to your prompt and go!
response = client.complete(
    context='',
    prompt = 'What is anarchy?'
)
print(
    response, file=sys.stderr
) # Anarchy is a political system in which the state is abolished and the people are free...
```

**Comment by AfamO** [comment]
It's alright. The above step, along with extra efforts to request for repo access from both Meta and Hugging Face websites, worked
