### ISSUE TITLE
structure web server as a use of library api

### ISSUE THREAD

**Issue by cartazio** [anarchy-ai/LLM-VM#58]
currently we have the library depends on the web server, when theres no good reason to require it

**Comment by dorkitude** [comment]
@cartazio can you explain a little more what you mean?  (does the library import from somewhere we don't need, or does it, like, force HTTP requests somewhere when it could access stuff internally?)

**Comment by roopeshsn** [comment]
Hi, @cartazio! I think they're independent already.

**Comment by mmirman** [comment]
@cartazio @abhigya-sodani is this closed?

**Comment by cartazio** [comment]
closing for now
