### ISSUE TITLE
Add support for other LLMs

### ISSUE THREAD

**Issue by Sauman9456** [anarchy-ai/LLM-VM#6]
List of open-source LLMs:

- [Huggingface](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard)
- [Wiki](https://en.wikipedia.org/wiki/Large_language_model)
- [Awesome-LLM(GitHub)](https://github.com/Hannibal046/Awesome-LLM)

<html>
<body>

Name | Release date[a] | Developer | Number of parameters[b] | Corpus size | License[c] | Notes
-- | -- | -- | -- | -- | -- | --
BERT | 2018 | Google | 340 million[42] | 3.3 billion words[42] | Apache 2.0[43] | An early and influential language model,[2] but encoder-only and thus not built to be prompted or generative[44]
XLNet | 2019 | Google | ~340 million[45] | 33 billion words |   | An alternative to BERT; designed as encoder-only[46][47]
GPT-2 | 2019 | OpenAI | 1.5 billion[48] | 40GB[49] (~10 billion tokens)[50] | MIT[51] | general-purpose model based on transformer architecture
GPT-3 | 2020 | OpenAI | 175 billion[25] | 300 billion tokens[50] | public web API | A fine-tuned variant of GPT-3, termed GPT-3.5, was made available to the public through a web interface called ChatGPT in 2022.[52]
GPT-Neo | March 2021 | EleutherAI | 2.7 billion[53] | 825 GiB[54] | MIT[55] | The first of a series of free GPT-3 alternatives released by EleutherAI. GPT-Neo outperformed an equivalent-size GPT-3 model on some benchmarks, but was significantly worse than the largest GPT-3.[55]
GPT-J | June 2021 | EleutherAI | 6 billion[56] | 825 GiB[54] | Apache 2.0 | GPT-3-style language model
Megatron-Turing NLG | October 2021[57] | Microsoft and Nvidia | 530 billion[58] | 338.6 billion tokens[58] | Restricted web access | Standard architecture but trained on a supercomputing cluster.
Ernie 3.0 Titan | December 2021 | Baidu | 260 billion[59] | 4 Tb | Proprietary | Chinese-language LLM. Ernie Bot is based on this model.
Claude[60] | December 2021 | Anthropic | 52 billion[61] | 400 billion tokens[61] | Closed beta | Fine-tuned for desirable behavior in conversations.[62]
GLaM (Generalist Language Model) | December 2021 | Google | 1.2 trillion[63] | 1.6 trillion tokens[63] | Proprietary | Sparse mixture-of-experts model, making it more expensive to train but cheaper to run inference compared to GPT-3.
Gopher | December 2021 | DeepMind | 280 billion[64] | 300 billion tokens[65] | Proprietary |  
LaMDA (Language Models for Dialog Applications) | January 2022 | Google | 137 billion[66] | 1.56T words,[66] 168 billion tokens[65] | Proprietary | Specialized for response generation in conversations.
GPT-NeoX | February 2022 | EleutherAI | 20 billion[67] | 825 GiB[54] | Apache 2.0 | based on the Megatron architecture
Chinchilla | March 2022 | DeepMind | 70 billion[68] | 1.4 trillion tokens[68][65] | Proprietary | Reduced-parameter model trained on more data. Used in the Sparrow bot.
PaLM (Pathways Language Model) | April 2022 | Google | 540 billion[69] | 768 billion tokens[68] | Proprietary | aimed to reach the practical limits of model scale
OPT (Open Pretrained Transformer) | May 2022 | Meta | 175 billion[70] | 180 billion tokens[71] | Non-commercial research[d] | GPT-3 architecture with some adaptations from Megatron
YaLM 100B | June 2022 | Yandex | 100 billion[72] | 1.7TB[72] | Apache 2.0 | English-Russian model based on Microsoft's Megatron-LM.
Minerva | June 2022 | Google | 540 billion[73] | 38.5B tokens from webpages filtered for mathematical content and from papers submitted to the arXiv preprint server[73] | Proprietary | LLM trained for solving "mathematical and scientific questions using step-by-step reasoning".[74] Minerva is based on PaLM model, further trained on mathematical and scientific data.
BLOOM | July 2022 | Large collaboration led by Hugging Face | 175 billion[75] | 350 billion tokens (1.6TB)[76] | Responsible AI | Essentially GPT-3 but trained on a multi-lingual corpus (30% English excluding programming languages)
Galactica | November 2022 | Meta | 120 billion | 106 billion tokens[77] | CC-BY-NC-4.0 | Trained on scientific text and modalities.
AlexaTM (Teacher Models) | November 2022 | Amazon | 20 billion[78] | 1.3 trillion[79] | public web API[80] | bidirectional sequence-to-sequence architecture
LLaMA (Large Language Model Meta AI) | February 2023 | Meta | 65 billion[81] | 1.4 trillion[81] | Non-commercial research[e] | Trained on a large 20-language corpus to aim for better performance with fewer parameters.[81] Researchers from Stanford University trained a fine-tuned model based on LLaMA weights, called Alpaca.[82]
GPT-4 | March 2023 | OpenAI | Exact number unknown, approximately 1 trillion [f] | Unknown | public web API | Available for ChatGPT Plus users and used in several products.
Cerebras-GPT | March 2023 | Cerebras | 13 billion[84] |   | Apache 2.0 | Trained with Chinchilla formula.
Falcon | March 2023 | Technology Innovation Institute | 40 billion[85] | 1 Trillion tokens (1TB)[85] | Apache 2.0[86] | The model is claimed to use only 75% of GPT-3's training compute, 40% of Chinchilla's, and 80% of PaLM-62B's.
BloombergGPT | March 2023 | Bloomberg L.P. | 50 billion | 363 billion token dataset based on Bloomberg's data sources, plus 345 billion tokens from general purpose datasets[87] | Proprietary | LLM trained on financial data from proprietary sources, that "outperforms existing models on financial tasks by significant margins without sacrificing performance on general LLM benchmarks"
PanGu-Σ | March 2023 | Huawei | 1.085 trillion | 329 billion tokens[88] | Proprietary |  
OpenAssistant[89] | March 2023 | LAION | 17 billion | 1.5 trillion tokens | Apache 2.0 | Trained on crowdsourced open data
PaLM 2 (Pathways Language Model 2) | May 2023 | Google | 340 billion[90] | 3.6 trillion tokens[90] | Proprietary | Used in Bard chatbot.[91]

</body>
</html>

**Comment by Sauman9456** [comment]
Added Wiki

**Comment by mmirman** [comment]
@Sauman9456 Thanks for adding this it is spot on!  This is a lot of work depending on where it gets added because you need to test agents with new LLMs, but would be great 😃

**Comment by shivance** [comment]
Hi @mmirman , I'm interested in contributing here. I've experience in building LLMs and currently working at https://github.com/keras-team/keras-nlp . How can I get started.

**Comment by mmirman** [comment]
@shivance Apologies for the slow reply here!   The best way to get started is to ping #engineering in the discord.  

@cartazio Can we get an update on this somehow?

**Comment by shivance** [comment]
@mmirman I already reached out on the discord server on the channels and DMs but no one replied. Thanks, I would like to pass!

**Comment by mmirman** [comment]
@shivance Apologies for that! This month has been a bit of chaos with the influx of interest.  We really value every community member and are working to put processes in place to ensure we don't miss messages like yours again.

**Comment by kingjuno** [comment]
@mmirman I would like to work on this.

**Comment by cartazio** [comment]
at this point we're tracking only adding new OSS models that achieve state of the art performance and or achieve new levels of efficiency for a given quality target. If theres specific models that are missing that have serious benefits, please highlight them, closing for now
