### ISSUE TITLE
Load compatibility with Bert models into onsite_llm.py

### ISSUE THREAD

**Issue by ajn2004** [anarchy-ai/LLM-VM#69]
Create a Small_Local_Bert class capable of managing the bert LLM similar to other code in the file.

**Comment by ajn2004** [comment]
Strongly recommend to study the Small_Local_Neo class and build Small_Local_Bert around that logic.

**Comment by dorkitude** [comment]
Done.  Thanks @ajitalapati!

**Comment by mmirman** [comment]
@ajitalapati please send me an email and I will send you a swag code!
