### ISSUE TITLE
Add LLM Quantization

### ISSUE THREAD

**Issue by Sauman9456** [anarchy-ai/LLM-VM#7]
QLoRA (an efficient finetuning approach that reduces memory usage enough to finetune a 65B parameter model on a single 48GB GPU while preserving full 16-bit finetuning task performance).
Converting LMMs to 4-bit quantized with QLoRA will reduce the required resources, speed up the fine-tuning and inference parts, and be much cheaper.

Refer to the following link for your reference 

- [https://github.com/artidoro/qlora](https://github.com/artidoro/qlora)

- [https://huggingface.co/blog/4bit-transformers-bitsandbytes](https://huggingface.co/blog/4bit-transformers-bitsandbytes)

**Comment by vivasvan1** [comment]
Is this issue still open?

**Comment by fracapuano** [comment]
Hey there! Would love to contribute on this. Is the issue still open?

**Comment by VictorOdede** [comment]
Hey @vivasvan1 @fracapuano this issue was replaced by #222 and #223

**Comment by VictorOdede** [comment]
replaced by #222 and #223

**Comment by VictorOdede** [comment]
replaced by https://github.com/anarchy-ai/LLM-VM/issues/222 and https://github.com/anarchy-ai/LLM-VM/issues/223
