### ISSUE TITLE
add correct model persistence for Local LLM models

### ISSUE THREAD

**Issue by cartazio** [anarchy-ai/LLM-VM#71]
currently, finetuning doesn't persist models after they've been fine tuned

**Comment by dorkitude** [comment]
I'm interested in helping with this.  Do you think it's to bring in SQLite?

**Comment by abhigya-sodani** [comment]
Doesn't it save the models to the home/.models file locally?

**Comment by cartazio** [comment]
I think Kyle was thinking more about having a versioned store of all the
model metadate, absolutely agree that using the file system to store large
data blobs is the way to go

**Comment by abhigya-sodani** [comment]
Should we close this @cartazio

**Comment by cartazio** [comment]
sure, there should be a follow on ticket that makes local management sane though

**Comment by mmirman** [comment]
Is this being redone by https://github.com/TheRealVish @therealvish?
