### ISSUE TITLE
Add LoRA, QLoRA fine-tuning for HF models

### ISSUE THREAD

**Issue by VictorOdede** [anarchy-ai/LLM-VM#97]
Current onsite LLM class uses full parameter fine-tuning which costly. LoRA fine-tuning will require less memory and prevent overfitting by freezing the pretrained weights.

**Comment by cartazio** [comment]
yeah, sounds good

**Comment by bilal-aamer** [comment]
Hey @VictorOdede, I'd like to work on this.

**Comment by VictorOdede** [comment]
Kindly mention this in the engineering channel on Discord then @mmirman or @cartazio will give you the green light.

> Hey @VictorOdede, I'd like to work on this.

**Comment by mmirman** [comment]
@bilal-aamer We certainly won't stop you from working on it :-) but it'd be good to get on a call with @abhigya-sodani to see what is useful to know before starting it!

**Comment by bilal-aamer** [comment]
Sure will do! Did some due diligence already, need some pointers from @abhigya-sodani.

**Comment by abhigya-sodani** [comment]
sure bilal lets get on a call soon

**Comment by harivamsi9** [comment]
If someone is not actively working on this, I can take up this task

**Comment by cartazio** [comment]
Have at it!

**Comment by abhigya-sodani** [comment]
https://github.com/anarchy-ai/LLM-VM/issues/7 is also applicable/related to this ticket

**Comment by berkay3500** [comment]
Is there any team working on this issue?

**Comment by cartazio** [comment]
if youre confident you can bang something together, have at it! this one of the more complex open tickets, so be honest with yourself! that said, worst case you learn something!
